### ISSUE TITLE
Add publications?

### ISSUE THREAD

**Issue by HobnobMancer** [sipbs-compbiol/sipbs-compbiol.github.io#1]
## Summary

Is it worth adding publications to the website? Either as a dedicated page and/or to individuals' bio pages?

## Motivation

At present, prospective students, collaborators and future employers have to search the SIPBS webpage for our bios *and* the Strathclyde website for our publications. Including publications and awards on our bios or as a single page for the entire group could help highlight the group's achievements.

## Drawbacks

This information is already available via Strathclyde pure, and would require maintenance/updating. 

Possibly students could list their publications on their bio pages as they will (likely) have fewer publications to list.

Alternatively, the main page could have a 'Research Output' or 'Publications' button that links directly too @widdowquinn 's [Pure portal research output page](https://pureportal.strath.ac.uk/en/persons/leighton-pritchard/publications/)?

**Comment by widdowquinn** [comment]
I'm happy for group members to add any publications they like to their bios.

I think it might be worth having the most recent/significant publications on the front page[1]. But beyond that - as you note - the information is collated completely and automagically elsewhere (e.g. ORCID, Pure, ResearcherID, Google Scholar) and we'd have to manage it manually. I don't really want to do that. For my own bio, I link to these resources.

What do you think - five or so most recent/significant publications? After `What We Do` and before `Key Collaborators`?

[1] I think that maintaining a file to `<include/>`, rather than editing the main page manually, is the better way to go about this.

**Comment by HobnobMancer** [comment]
I think that sounds like a really good idea, it would help show off the groups work with minimal effort required for maintenance our end.

I don't currently know how to set that up. Is it included in the `https://github.com/mmistakes/minimal-mistakes` documentation? Or do you want to set up it?

**Comment by widdowquinn** [comment]
Including other `.html` files is a very general thing, e.g. https://www.w3schools.com/howto/howto_html_include.asp but `Jekyll` has its own way of doing it: https://jekyllrb.com/docs/includes/ 

We'd have something like a `current_publications.html` file (or `.md`? I don't know if that would work…) in the `_includes` folder at the site root, and then have:

```jekyll
{% include current_publications.html %} on the main page.
```

 in the appropriate location.

**Comment by HobnobMancer** [comment]
Looking at the `Jekyll` repo, I think we can include `.md` files by using the [ include_remote plugins](https://github.com/jekyll/jekyll/issues/8738), but it may not render the way we expect, someone recently raised an issue saying [`.md` files do not render in HTML when included](https://github.com/jekyll/jekyll/issues/8994).


Do you want the publications stored in a table, e.g.:
| Date       | Journal                  | Publication                                      | DOI                       |
|------------|--------------------------|--------------------------------------------------|---------------------------|
| 2022       | Fontiers in Microbiology | Pritchard, L., ... (2022) 'Title', Journal, .... | [doi.org/10.3389/fmicb.2022.887310](https://doi.org/10.3389/fmicb.2022.887310) |  

Or a list (with or without bullet points), e.g.:  

Hobbs, Emma E. M.; Pritchard, Leighton; Chapman, Sean; Gloster, Tracey M. (2021): cazy_webscraper: For creating a local CAZyme database. figshare. Poster. [doi.org/10.6084/m9.figshare.14370860](https://doi.org/10.6084/m9.figshare.14370860.v7)

Hobbs, Emma E. M.; Gloster, Tracey M.; Chapman, Sean; Pritchard, Leighton (2021): Comprehensive evaluation of CAZyme prediction tools in fungal and bacterial species. figshare. Poster. [doi.org/10.6084/m9.figshare.14370836](https://doi.org/10.6084/m9.figshare.14370836.v3)

**Comment by widdowquinn** [comment]
I would have expected the `.md` files not to be parsed into HTML, so the reported behaviour in [https://github.com/jekyll/jekyll/issues/8994](https://github.com/jekyll/jekyll/issues/8994) seems right.

I think a list with DOI link is the better option - easier to cut and paste. Not using `<UL>`/bullet points might be neater - but try it both ways and see what you think.
